### ISSUE TITLE
Include an SCP option?

### ISSUE THREAD

**Issue by sdavids13** [int128/groovy-ssh#68]
I know this might seem redundant with the SFTP functionality, but there are cases where SFTP doesn't work and SCP does. It would be great to allow the someone to use scp in the 'put' file operation, kind of how pscp allows the either with a flag: http://the.earth.li/~sgtatham/putty/0.60/htmldoc/Chapter5.html (`-scp` or `-sftp`)

**Comment by int128** [comment]
SCP function is currently not implemented yet but seems possible with JSch. Future release will support it.

Examples:
http://www.jcraft.com/jsch/examples/ScpTo.java.html
http://www.jcraft.com/jsch/examples/ScpFrom.java.html

**Comment by jordihs** [comment]
I was about to open the same issue. I am working on a script that uploads files to a server that has SFTP disabled so my only choice is to use SCP for file transfer. I could use ant SCP task but that takes away all the benefits of using your library. 
Also, I should mention that there is a bug in the SFTP implementation that I found trying to send files to this server with SFTP disabled. Your code looks like this: 
`try {
            channel.connect()
            log.debug("SFTP #${channel.id} started")
            callWithDelegate(closure, new SftpOperations(channel))
        } finally {
            channel.disconnect()
            log.debug("SFTP #${channel.id} closed")
        }`
[sorry but the comment system does not respect indentation or linefeeds]
There is no catch for exceptions, so in my case, what happens is that the log statement in the finally block is esecuted but since channel.connect() throws an exception, the first log statement is not displayed. I get this log trace: 

> 19:01:25.070 [DEBUG] [org.hidetake.groovy.ssh.operation.DefaultOperations] SFTP #1 closed
19:01:25.070 [DEBUG] [org.hidetake.groovy.ssh.connection.ConnectionManager] Waiting for pending operations

And the script hangs since the put operation never completes. 
Kudos for this great work in the library, I hope you will soon add the SCP feature so that I can use it for my project. Thanks a lot.

**Comment by jordihs** [comment]
By the way, I started writing that script a couple years ago, using version 0.2.0. Since it wasn't implemented I pulled the project and implemented the put operation. I have attached the relevant script with a scp() method that, if I recall correctly, does the job. Obviously the library has changed a lot but thtat bit of code might still help if you decide to implement the feature. Unfortunately I had no time (and still lack it) to implement the get operation, but hopefully this should help you get started with this. 
One note about this: I believe it will be hard to implement the put method that takes an input stream, at least without reading it fulle before the transfer, because the SCP command requires that you state the size of the transfered file beforehand. 
And one suggestion: Ideally, you should be able to set a flag in the remote server definition to use SCP instead of SFTP for file transfers. 
Again, thanks for your great work. Cheers. 
[DefaultOperationHandler.zip](https://github.com/int128/groovy-ssh/files/107950/DefaultOperationHandler.zip)

**Comment by int128** [comment]
@jordihs Thank you for the contribution. I will try to merge SCP feature.

**Comment by breskeby** [comment]
Hey, what is the status of this ticket? scp would be really awesome to have.

**Comment by int128** [comment]
Still work in progress. SCP support will be shipped in the next release.

**Comment by int128** [comment]
Released 2.1.0 now. It works fine but performance will be improved in the future.

@jordihs Thanks for your contribution. Your code helps me.
